from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

SKIDL_lib_version = '0.0.1'

skidl_lib = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'Q', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'Bipolar Junction Transistor', 'keywords':'bipolar transistor npn pnp', 'model':'2n2222a', '_match_pin_regex':False, '_aliases':Alias({'bjt', 'BJT'}), 'pyspice':{'name': 'Q', 'kw': {'model': 'model', 'area': 'area', 'areab': 'areab', 'areac': 'areac', 'multiplier': 'multiplier', 'm': 'multiplier', 'off': 'off', 'ic': 'initial_condition', 'initial_condition': 'initial_condition', 'temp': 'temperature', 'temperature': 'temperature', 'dtemp': 'device_temperature', 'device_temperature': 'device_temperature', 'c': 'collector', 'b': 'base', 'e': 'emitter', 's': 'substrate'}, 'add': <function add_part_to_circuit at 0x7efeb427e830>}, 'ref_prefix':'Q', 'num_units':1, 'fplist':None, 'do_erc':True, 'aliases':Alias({'bjt', 'BJT'}), 'pin':None, 'footprint':None, 'pins':[
            Pin(num='1',name='c',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='b',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='3',name='e',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='4',name='s',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'V', 'dest':TEMPLATE, 'tool':SKIDL, 'dc_value':UnitValue(5 V), 'description':'Voltage source', 'keywords':'voltage source', '_match_pin_regex':False, '_aliases':Alias({'AMMETER', 'ammeter', 'vs', 'v', 'VS'}), 'pyspice':{'name': 'V', 'kw': {'value': 'dc_value', 'dc_value': 'dc_value', 'p': 'plus', 'n': 'minus'}, 'add': <function add_part_to_circuit at 0x7efeb427e830>}, 'ref_prefix':'V', 'num_units':1, 'fplist':None, 'do_erc':True, 'aliases':Alias({'AMMETER', 'ammeter', 'vs', 'v', 'VS'}), 'pin':None, 'footprint':None, 'pins':[
            Pin(num='1',name='p',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='n',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'Resistor', '_match_pin_regex':False, 'pyspice':{'name': 'R', 'kw': {'value': 'resistance', 'resistance': 'resistance', 'ac': 'ac', 'multiplier': 'multiplier', 'm': 'multiplier', 'scale': 'scale', 'temp': 'temperature', 'temperature': 'temperature', 'dtemp': 'device_temperature', 'device_temperature': 'device_temperature', 'noisy': 'noisy', 'p': 'plus', 'n': 'minus'}, 'add': <function add_part_to_circuit at 0x7efeb427e830>}, 'keywords':'res resistor', 'ref_prefix':'R', 'num_units':1, 'fplist':None, 'do_erc':True, 'aliases':Alias(), 'pin':None, 'footprint':None, 'pins':[
            Pin(num='1',name='p',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='n',func=Pin.types.PASSIVE,do_erc=True)] }),
        Part(**{ 'name':'SINEV', 'dest':TEMPLATE, 'tool':SKIDL, 'description':'Sinusoidal voltage source', 'frequency':FrequencyValue(1 kHz), 'amplitude':UnitValue(0.01 V), 'keywords':'sinusoidal voltage source', '_match_pin_regex':False, '_aliases':Alias({'sinev', 'sinusoidalvoltage', 'SINUSOIDALVOLTAGE'}), 'pyspice':{'name': 'SinusoidalVoltageSource', 'kw': {'dc_offset': 'dc_offset', 'ac_magnitude': 'ac_magnitude', 'ac_phase': 'ac_phase', 'offset': 'offset', 'amplitude': 'amplitude', 'frequency': 'frequency', 'delay': 'delay', 'damping_factor': 'damping_factor', 'p': 'node_plus', 'n': 'node_minus'}, 'add': <function add_part_to_circuit at 0x7efeb427e830>}, 'ref_prefix':'V', 'num_units':1, 'fplist':None, 'do_erc':True, 'aliases':Alias({'sinev', 'sinusoidalvoltage', 'SINUSOIDALVOLTAGE'}), 'pin':None, 'footprint':None, 'pins':[
            Pin(num='1',name='p',func=Pin.types.PASSIVE,do_erc=True),
            Pin(num='2',name='n',func=Pin.types.PASSIVE,do_erc=True)] })])